### ISSUE TITLE
Storeable entities

### ISSUE THREAD

**Issue by Yelnats321** [Yelnats321/EntityPlus#13]
Currently you are prohibited from storing entities. Rather, altering an entity will invalidate any previous reference to it. This restriction is made so that you can have caching on the entity side for `has_(tag/component)`. Although the case can be made that the restriction is not worth it for an`O(1) has_component`, the main feature of tags is their low overhead and so removing `O(1) has_tag` is detrimental to that, making them obsolete in terms of performance. 

It seems useful for some applications to be able to store entities rather than having to query them each time. Without event integration this is not very useful, but with it the want for storeable entities is increased.

There are two options that I see for this feature. Either modify `entity` so that it has an `sync()` function, which will sync it up to its actual values inside `entity_manager`. The issue here is that I am not sure how to deal with the case where a sync reveals that the entity has been deleted. I can add a bool indicating this state but it just adds more complications for state checking and the like. However this can be alleviated by `sync()` returning an indication of if the entity is valid post sync.

The other option is to have another type that we would call an `entity_handle`. This would be a barebones storeable type that underneath only holds a pointer to its manager and an ID. You can get an `entity_handle` from an `entity` via `get_handle()` and also convert an `entity_handle` to an `entity` via `get_entity()`. The same problem exists as with the syncing if the entity was deleted in the meantime. This would probably mean that `get_entity()` will have to return a pointer or an optional, but without library support I am very hesitant with the latter option.

On the one hand the second option conveys more information because we know that `entity` is temporary, `entity_handle` is not. On the other hand having additional types is annoying and complicates code needlessly. I am leaning more towards the first option, especially because the interface can be much nicer.

**Comment by Tamschi** [comment]
To me this raises a few questions:
- Are components storable?
- Which time complexity would `sync()`/`get_entity()` have?

I think it would be fine to return a pointer from `get_entity()` as long as you can ensure it's `NULL`(?) if the entity doesn't exist to make sure cosuming code will segfault instead of accessing something unintended.

**Comment by Yelnats321** [comment]
No, components are not storeable. They are invalidated quite often actually, but updates to them can soon be synchronized with added event support.

The time complexity would be `O(log n)` in both cases, so choosing one over the other is mostly semantics.

**Comment by Yelnats321** [comment]
I think I'm going to go with `sync()` unless anyone has any objections.
