### ISSUE TITLE
Error C2737: 'entityplus::meta::delay_v': 'constexpr' object must be initialized

### ISSUE THREAD

**Issue by arnaud-jamin** [Yelnats321/EntityPlus#18]
Hello, 

I'm trying to use your library:

>cmake .
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23026.0
-- The CXX compiler identification is MSVC 19.0.23026.0
[...]

When building the solution from Visual Studio 2015, I get the following error message:

> \entityplus\metafunctions.h(26): error C2737: 'entityplus::meta::delay_v': 'constexpr' object must be initialized

Thanks

**Comment by Yelnats321** [comment]
Have you tried updating MSVC to update 3? There was additional `constexpr` support added in one of the updates and I am not sure which version 19.0.23026.0 is.

**Comment by Yelnats321** [comment]
Additionally there is a requirement to use Catch lib for the tests. To specify the library location use `-DCatch_dir=/path/to/catch/lib`. This might be changed since Catch uses boost licensing too so I might just distribute it alongside the tests.
