### ISSUE TITLE
The Future, C++17

### ISSUE THREAD

**Issue by Yelnats321** [Yelnats321/EntityPlus#20]
This project is currently in a bit of a limbo state. The version for all intents and purposes should be at 2.0, however I am afraid there are certain features/changes that are not backwards compatible that I want to make before I release, but have not had the time to sit down and examine the code thoroughly to make the change. I am currently very busy with school work, and I don't see it slowing down for at least a month or two.

With all this being said, I want to wait until GCC/Clang/MSVC support C++17, or at least most of the nice features that are coming with that standard version. I think that when that happens, I will rewrite a lot of the code to use these features and support C++17 only. This would mean nicer error codes and a more simplifications in the code. However, this may reduce the userbase of the library.

To combat this standard version bump, I will rewrite the code alongside a 2.0 release. That way, any features (or breaking changes) that occur as a natural result of the rewrite can be also ported into the 2.0 release. The rewrite will force me into the state of mind that I need to be in to further extend and enhance the library, as I have not touched the code for some time now. In effect, there will be a 2.0 and 3.0 release simultaneously, with the only difference between the two being compiler/standard version.

I don't know if a standard version increase is a deal breaker for any users (or potential users), so I would like to hear your input too.

**Comment by WarlockD** [comment]
Makes you feel better I was looking specifically for a C++17 library that handled events and enitys.  Got to love std::variant and std::visit.

**Comment by Yelnats321** [comment]
That's good to hear. Although I am not sure where variant would come into play.

**Comment by Yelnats321** [comment]
I am moving the codebase into C++17, which removes a lot of metaprogramming cruft and makes the code nicer to work with. Will make a complete transition once MSVC supports enough of the features I need (hopefully update 5, probably update 6).
