### ISSUE TITLE
Remove boost dependency

### ISSUE THREAD

**Issue by Yelnats321** [Yelnats321/EntityPlus#8]
Remove or incorporate that part of boost with the library. Look for a different container library instead.

**Comment by Yelnats321** [comment]
I've written replacements for the code but I want to review them more before pushing this change, Branch [no_boost](/Yelnats321/EntityPlus/tree/no_boost) was created for this.

**Comment by aggsol** [comment]
Container should be easy to unit test then.

**Comment by Yelnats321** [comment]
Yeah, I just haven't written enough of those yet. The containers also has non-const keys but the tests right now test that by modifying the keys that will affect sorting, which is fine but kind of iffy. I'll write more tests soon but if someone could have a look before pushing this update that'd be great.
